-- 1º BUSCAR O NOME E ANO DOS FILMES
SELECT
	Nome,
	Ano
FROM Filmes

-- 2º BUSCAR O NOME E ANO DOS FILMES, ORDENADOS POR ORDEM CRESCENTE PELO ANO
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
ORDER BY Ano 

-- 3º BUSCAR PELO FILME DE VOLTA PARA O FUTURO, TRAZENDO O NOME, ANO E A DURAÇÃO
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Nome = 'De Volta para O Futuro' 

-- 4º BUSCAR OS FILMES LANÇADOS EM 1997
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Ano = 1997 

-- 5º BUSCAR OS FILMES LANÇADOS APÓS O ANO 2000
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Ano > 2000

-- 6º BUSCAR OS FILMES COM A DURAÇÃO MAIOR QUE 100 E MENOR QUE 150, ORDENADO PELA DURAÇÃO EM ORDEM CRESCENTE
SELECT 
	Nome,
	Ano,
	Duracao
FROM Filmes
WHERE Duracao > 100 AND Duracao < 150
ORDER BY Duracao

-- 7º BUSCAR A QUANTIDADE DE FILMES LANÇADAS NO ANO, AGRUPANDO POR ANO, ORDENANDO PELA DURAÇÃO EM ORDEM DECRESCENTE
SELECT
	Ano,
	COUNT(*) Duracao
FROM Filmes
GROUP BY Ano
ORDER BY Duracao DESC
	
-- 8º BUSCAR OS ATORES DO GÊNERO MASCULINO, RETORNANDO O PRIMEIRO NOME E ULTIMO NOME
SELECT
	Id,
	PrimeiroNome,
	UltimoNome,
	Genero	
FROM Atores
WHERE Genero = 'M'

-- 9º BUSCAR OS ATORES DO GÊNERO FEMININO, RETORNANDO O PRIMEIRO NOME, ULTIMO NOME E ORDENANDO PELO PRIMEIRO NOME
SELECT
	Id,
	PrimeiroNome,
	UltimoNome,
	Genero	
FROM Atores
WHERE Genero = 'F'
ORDER BY PrimeiroNome

-- 10º BUSCAR O NOME DO FILME E O GÊNERO
SELECT
	F.Nome,
	G.Genero
FROM
	Filmes F
INNER JOIN
	FilmesGenero FG ON F.Id = FG.IdFilme
INNER JOIN
	Generos G ON G.Id = FG.IdGenero

-- 11º BUSCAR O NOME DO FILME E O GÊNERO DO TIPOE "MISTÉRIO"
SELECT
	F.Nome,
	G.Genero
FROM
	Filmes F
INNER JOIN
	FilmesGenero FG ON F.Id = FG.IdFilme
INNER JOIN
	Generos G ON G.Id = FG.IdGenero
WHERE G.Genero = 'Mistério'

-- BUSCAR O NOME DO FILME E OS ATORES, TRAZENDO O PRIMEIRO NOME, ULTIMO NOME E O PAPEL
SELECT
	F.Nome,
	A.PrimeiroNome,
	A.UltimoNome,
	EF.Papel
FROM
	Filmes F
INNER JOIN
	ElencoFilme EF ON F.Id = EF.IdFilme
INNER JOIN
	Atores A ON A.Id = EF.IdAtor
